[package]
name = "incresql"
version = "0.1.0"
authors = ["Tim Patterson <tim.wanaka@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "src/ast",
    "src/data",
    "src/executor",
    "src/functions",
    "src/parser",
    "src/planner"
]

[dependencies]

[profile.release]
debug = true
opt-level = 3
lto = "thin"
codegen-units = 1
