[package]
name = "planner"
version = "0.1.0"
authors = ["Tim Patterson <tim.wanaka@gmail.com>"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }

[dev-dependencies]
data = { path = "../data" }